### ISSUE TITLE
"No such compiler 'eclipse'." with 3.15.0 and Maven 3.9.6

### ISSUE THREAD

**Issue by stormeuh** [codehaus-plexus/plexus-compiler#394]
Hello

I am getting "No such compiler 'eclipse'" on a completely bare project (generated from maven quickstart archetype).
Below is my pom.xml, and here is the log from running "mvn clean compile -X"
[mvn_clean_compile.log](https://github.com/user-attachments/files/16015224/mvn_clean_compile.log)

Quick summary of my environment (see attached log for more):
Fedora 40
Java 21.0.3 OpenJDK
Maven 3.9.6

```
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-assembly-plugin</artifactId>
      <version>3.4.2</version>
      <type>maven-plugin</type>
    </dependency>
    <dependency>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>${maven.compiler.version}</version>
      <type>maven-plugin</type>
    </dependency>
  </dependencies>
  <properties>
    <plexus.compiler.version>2.15.0</plexus.compiler.version>
    <maven.compiler.version>3.13.0</maven.compiler.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.version}</version>
        <configuration>
          <compilerId>eclipse</compilerId>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-api</artifactId>
            <version>${plexus.compiler.version}</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-manager</artifactId>
            <version>${plexus.compiler.version}</version>
          </dependency>
          <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-compiler-eclipse</artifactId>
            <version>${plexus.compiler.version}</version>
          </dependency>
        </dependencies>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
          <archive>
            <manifest>
              <mainClass>com.mycompany.app.App</mainClass>
            </manifest>
          </archive>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

**Comment by itineric** [comment]
same here, any clues ?

**Comment by pzygielo** [comment]
Cannot reproduce.
With the pom as above I'm getting:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.mycompany.app:my-app >----------------------
[INFO] Building my-app 1.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ my-app ---
[INFO] Deleting /tmp/ec/target
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ my-app ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /tmp/ec/src/main/resources
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ my-app ---
[INFO] Recompiling the module because of changed source code.
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling with eclipse [debug target 21] to target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.109 s
[INFO] Finished at: 2024-10-21T14:07:35+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by pzygielo** [comment]
Also - not sure what is 3.15.0 in the title for, as plexus-compiler is 2.15.0 and m-compiler-p is 3.13.0.

**Comment by itineric** [comment]
Problem starts with plexus-compiler-eclipse version 2.14.0

I used the given pom.xml and run mvn install -Dsisu.debug
I got this error:

```
TRACE: Sisu - Problem scanning: jar:file:/home/me/.m2/repository/org/codehaus/plexus/plexus-compiler-eclipse/2.15.0/plexus-compiler-eclipse-2.15.0.jar!/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.class
java.lang.IllegalArgumentException
	at org.eclipse.sisu.space.asm.ClassReader.<init>(ClassReader.java:170)
	at org.eclipse.sisu.space.asm.ClassReader.<init>(ClassReader.java:153)
	at org.eclipse.sisu.space.asm.ClassReader.<init>(ClassReader.java:424)
	at org.eclipse.sisu.space.SpaceScanner.accept(SpaceScanner.java:102)
	at org.eclipse.sisu.space.SpaceScanner.accept(SpaceScanner.java:78)
	at org.eclipse.sisu.space.SpaceModule.scanForElements(SpaceModule.java:168)
	at org.eclipse.sisu.space.SpaceModule.configure(SpaceModule.java:129)
	at org.eclipse.sisu.plexus.PlexusAnnotatedBeanModule.configure(PlexusAnnotatedBeanModule.java:102)
	at org.eclipse.sisu.plexus.PlexusBindingModule.configure(PlexusBindingModule.java:63)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.spi.Elements.getElements(Elements.java:96)
	at org.eclipse.sisu.wire.WireModule.configure(WireModule.java:75)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.google.inject.Guice.createInjector(Guice.java:59)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
	at org.codehaus.plexus.DefaultPlexusContainer.discoverComponents(DefaultPlexusContainer.java:460)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.discoverPluginComponents(DefaultMavenPluginManager.java:436)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:415)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:374)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:234)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
TRACE: Sisu - Add publisher: com.google.inject.internal.InjectorImpl@39e67516
```

Tried with several java 17 JDKs and maven from version 3.6.3 to 3.9.1, I always have the same error.

**Comment by itineric** [comment]
It works with maven 3.9.6+ as specified in 2.14.0 release notes.
Error should be a little more explicit.

@stormeuh: are you sure you are using the minimal required versions? see here: https://github.com/codehaus-plexus/plexus-compiler/releases/tag/plexus-compiler-2.14.0

**Comment by fdelapena** [comment]
This could be Fedora/RedHat specific (not tested with upstream maven). Maven 3.9.6, java and javac 21 and 23 from Red Hat's OpenJDK (without JAVA_HOME) and GraalVM CE (with JAVA_HOME set), same issue with 2.14.0 and 2.15.0, both tried from POM or from property from CLI as `-Dmaven.compiler.compilerId=eclipse`. 2.13.0 using ecj 3.39.0 works as expected. Using maven-compiler-plugin 3.13.0 in all tests.

**Comment by fdelapena** [comment]
Confirmed it's a Fedora packaging issue, likely because it relies on sisu 0.3.5.

After updating to downstream maven-3.9.6-8.fc42, maven-libs-3.9.6-8.fc42 and maven-openjdk21-3.9.6-8.fc42 and sisu-0.9.0M3.fc42 builds from rawhide, the issue gets fixed here.

Workaround for affected users (tested on Fedora 41, maybe works on 40 as well):

```
cd $(xdg-user-dir DOWNLOAD)
wget https://kojipkgs.fedoraproject.org//packages/maven/3.9.6/8.fc42/noarch/maven{,-lib,-openjdk21}-3.9.6-8.fc42.noarch.rpm
wget https://kojipkgs.fedoraproject.org//packages/sisu/0.9.0~M3/1.fc42/noarch/sisu-0.9.0~M3-1.fc42.noarch.rpm
sudo dnf install ./maven{,-lib,-openjdk21}-3.9.6-8.fc42.noarch.rpm ./sisu-0.9.0~M3-1.fc42.noarch.rpm
```
