### ISSUE TITLE
[plexus-compiler-j2objc] - tests are broken.

### ISSUE THREAD

**Issue by ethiclab** [codehaus-plexus/plexus-compiler#6]
Hello,

Currently it is not possible to issue an:

```
mvn clean package
```

due to a the following error:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.codehaus.plexus.compiler.j2objc.J2ObjCCompilerTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.07 sec <<< FAILURE! - in org.codehaus.plexus.compiler.j2objc.J2ObjCCompilerTest
testJ2ObjCCompiler(org.codehaus.plexus.compiler.j2objc.J2ObjCCompilerTest)  Time elapsed: 0.06 sec  <<< FAILURE!
junit.framework.AssertionFailedError
    at junit.framework.Assert.fail(Assert.java:47)
    at junit.framework.Assert.assertTrue(Assert.java:20)
    at junit.framework.Assert.assertTrue(Assert.java:27)
    at org.codehaus.plexus.compiler.j2objc.J2ObjCCompilerTest.testJ2ObjCCompiler(J2ObjCCompilerTest.java:62)


Results :

Failed tests: 
  org.codehaus.plexus.compiler.j2objc.J2ObjCCompilerTest#testJ2ObjCCompiler AssertionFailedError

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Plexus Compiler ................................... SUCCESS [  1.489 s]
[INFO] Plexus Compiler Api ............................... SUCCESS [  2.257 s]
[INFO] Plexus Compiler Manager ........................... SUCCESS [  0.707 s]
[INFO] Plexus Compiler Test Harness ...................... SUCCESS [  0.302 s]
[INFO] Plexus Compilers .................................. SUCCESS [  0.024 s]
[INFO] Plexus AspectJ Compiler ........................... SUCCESS [  2.037 s]
[INFO] Plexus C# Compiler ................................ SUCCESS [  0.538 s]
[INFO] Plexus Eclipse Compiler ........................... SUCCESS [  1.722 s]
[INFO] Plexus Jikes Compiler ............................. SUCCESS [  0.172 s]
[INFO] Plexus Javac Component ............................ SUCCESS [  2.423 s]
[INFO] Plexus Javac+error-prone Component ................ SUCCESS [  0.199 s]
[INFO] Plexus J2ObjC Compiler ............................ FAILURE [  0.414 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.677 s
[INFO] Finished at: 2015-05-25T21:09:55+01:00
[INFO] Final Memory: 32M/450M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project plexus-compiler-j2objc: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/montoyaedu/plexus-compiler/plexus-compilers/plexus-compiler-j2objc/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :plexus-compiler-j2objc
```

It works by issuing:

```
mvn -DskipTests=true
```

Just wondering if this behaviour known and wanted.

Regards,

EthicLab.

**Comment by rastaman** [comment]
Hi,
Could you let us know which version of j2objc do you use ? The code has probably not been updated to use new release of j2objc.

Best regards
